### ISSUE TITLE
Question about fragmentization

### ISSUE THREAD

**Issue by Gloria-LIU** [qiangbo1222/HierDiff#2]
Hello! Thank you for sharing this amazing work. 

I have a few questions and suggestions regarding some technical details:

1. Multi-hop conflicts: It would be helpful if you could provide further elaboration on the concept of multi-hop conflicts. Specifically, could you explain why the situation depicted in Figure 2 is considered a two-hop conflict? Alternatively, could it be understood as a scenario involving multiple neighbors conflicting with a single fragment?

2. Fragment vocabulary construction: In the process of constructing the fragment vocabulary, it would be valuable to determine whether there are any instances where a pair of fragments could potentially share a bond between them. Based on the fragment graph definition, it appears that neighboring fragments might have shared bonds or atoms. However, the appendix mentions running a minimum spanning tree algorithm on the graph to remove overlapping edges. To ensure clarity, could you specify how you handle fused/bridged rings—are they considered as one fragment or two fragments? 

3. Fragment edge types: How do you define the edges between fragments? Are they limited to binary types, or do you have multiple edge types indicating different combinations? Additionally, it would be useful to understand how you define the edge types for the output of the edge prediction network $\phi_{edge}$. 

Thank you in advance!

**Comment by qiangbo1222** [comment]
Thank you for your interest in our work.
1. Your understanding is correct. 2-hop conflicts occur when we examine edges independently, there are enough atoms/bonds that could be merged to form the edges, but when adjoint edges are examined together, there are conflicts since the center fragment has limited atoms/ bonds. 
2.  The intuition here is in most cases fragments shared atoms to establish edges. Bonds are shared only when two single rings are merged together to form a fused ring system. You could check the [JT-VAE paper](https://arxiv.org/pdf/1802.04364) for more detailed implementation, we make minor modifications to their algorithm for handling ring systems. Our main contribution here is using a 3D system to represent the fragment graph.
3. In fact, all edges are homogeneous in our model. We utilized local structure RMSD predicted by RDkit later to find the optimal attachments along linked fragments.

**Comment by qiangbo1222** [comment]
We will release the code before the official opening of ICML conference.

**Comment by Gloria-LIU** [comment]
Hi Bo,

Thank you for the detailed explanation and sharing the code! 
I think the google drive link to the preprocessed datasets (GEOM) is not accessible. Could you fix the sharing config? Thank you!

**Comment by qiangbo1222** [comment]
Thanks for your suggestion. I have updated the sharing config for my google drive. It should be ready for download now.

**Comment by qiangbo1222** [comment]
We have made all of our processed data from google drive publicly available, so we close this issue.
