### ISSUE TITLE
About Conditional Generation Experiments 

### ISSUE THREAD

**Issue by Gloria-LIU** [qiangbo1222/HierDiff#5]
Hello Bo,

Thank you for your great work!

I have a couple of questions about the drug-likeness properties task (Appendix C.6) in your paper:

1. Could you please specify the dataset used for these results? I couldn't find this information in the paper.

2. I'm having difficulty reproducing the SA Score and LogP task results. My implementation yields a significantly higher MAE (approximately 1.3) and MSE (around 2.6) compared to the paper's reported values (0.051 and 0.184). Is there any crucial setting or detail I might be missing?

Your insights would be greatly appreciated.

**Comment by qiangbo1222** [comment]
Hello,
Thank you for expressing interest in our research.
The results were produced using a model trained on the Geom-Drug dataset. Typically, we normalize the SA and LogP values to a range between 0 and 1, which serves as the condition for our diffusion model. I plan to update the code (hopefully in Feb) to clarify this point after the ICML submission deadline. I apologize for any confusion that may have arisen.

**Comment by qiangbo1222** [comment]
Hi Gloria,
I am sorry for the delay. Because I have left AIR for about a year. I have just recovered part of the code for reproducing the results. Sadly, the original conditional generation code is missing and I found it hard to find the range of conditions I have used for the conditional generation experiments. I might need a little bit more time to update this code repo. I will send you an email once I have finished it.
